version: "3.0"

services:
  json-server:
    image: vimagick/json-server
    command: --host 0.0.0.0 -p 3030 -w db.json
    ports:
      - 3030:3030
    volumes:
      - .:/data
    restart: always
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./dist:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80